const fKey = document.getElementById('f')
const fsKey = document.getElementById('fs')
const gKey = document.getElementById('g')
const gsKey = document.getElementById('gs')
const aKey = document.getElementById('a')
const asKey = document.getElementById('as')
const bKey = document.getElementById('b')
const cKey = document.getElementById('c')
const csKey = document.getElementById('cs')
const dKey = document.getElementById('d')
const dsKey = document.getElementById('ds')
const eKey = document.getElementById('e')
const f2Key = document.getElementById('f2')
const fs2Key = document.getElementById('fs2')
const g2Key = document.getElementById('g2')
const gs2Key = document.getElementById('gs2')
const a2Key = document.getElementById('a2')
const as2Key = document.getElementById('as2')
const b2Key = document.getElementById('b2')
const c2Key = document.getElementById('c2')
const cs2Key = document.getElementById('cs2')
const d2Key = document.getElementById('d2')
const ds2Key = document.getElementById('ds2')
const e2Key = document.getElementById('e2')



function playSound(url) {
    new Audio(url).play()
}

fKey.addEventListener('click', ()=> playSound('24-piano-keys/1.mp3'))
fsKey.addEventListener('click', ()=> playSound('24-piano-keys/2.mp3'))
gKey.addEventListener('click', ()=> playSound('24-piano-keys/3.mp3'))
gsKey.addEventListener('click', ()=> playSound('24-piano-keys/4.mp3'))
aKey.addEventListener('click', ()=> playSound('24-piano-keys/5.mp3'))
asKey.addEventListener('click', ()=> playSound('24-piano-keys/6.mp3'))
bKey.addEventListener('click', ()=> playSound('24-piano-keys/7.mp3'))
cKey.addEventListener('click', ()=> playSound('24-piano-keys/8.mp3'))
csKey.addEventListener('click', ()=> playSound('24-piano-keys/9.mp3'))
dKey.addEventListener('click', ()=> playSound('24-piano-keys/10.mp3'))
dsKey.addEventListener('click', ()=> playSound('24-piano-keys/11.mp3'))
eKey.addEventListener('click', ()=> playSound('24-piano-keys/12.mp3'))
f2Key.addEventListener('click', ()=> playSound('24-piano-keys/13.mp3'))
fs2Key.addEventListener('click', ()=> playSound('24-piano-keys/14.mp3'))
g2Key.addEventListener('click', ()=> playSound('24-piano-keys/15.mp3'))
gs2Key.addEventListener('click', ()=> playSound('24-piano-keys/16.mp3'))
a2Key.addEventListener('click', ()=> playSound('24-piano-keys/17.mp3'))
as2Key.addEventListener('click', ()=> playSound('24-piano-keys/18.mp3'))
b2Key.addEventListener('click', ()=> playSound('24-piano-keys/19.mp3'))
c2Key.addEventListener('click', ()=> playSound('24-piano-keys/20.mp3'))
cs2Key.addEventListener('click', ()=> playSound('24-piano-keys/21.mp3'))
d2Key.addEventListener('click', ()=> playSound('24-piano-keys/22.mp3'))
ds2Key.addEventListener('click', ()=> playSound('24-piano-keys/23.mp3'))
e2Key.addEventListener('click', ()=> playSound('24-piano-keys/24.mp3'))
